apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
- name: plausible2
  newName: ghcr.io/plausible/community-edition # new image >= v2.1.0
  #newName: plausible/analytics # old image < v2.1.0
  newTag: 'v2.1.0'