apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
images:
  - name: postgis
    newName: postgis/postgis
    newTag: "16-3.5-alpine"
