apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-djnd-pvc
  labels:
    app: postgresql-djnd
spec:
  storageClassName: "scw-bssd-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
