apiVersion: v1
kind: Secret
metadata:
  name: bugsink-secrets
type: Opaque
stringData:
  SECRET_KEY: changeme
  DATABASE_URL: postgresql://bugsink:changeme@database:5432/bugsink
  SITE_TITLE: DJND Bugsink
  BASE_URL: https://bugsink.example.org
  BEHIND_HTTPS_PROXY: "True"
  SINGLE_TEAM: "True"
  USER_REGISTRATION: CB_MEMBERS
  TIME_ZONE: Europe/Ljubljana
  EMAIL_HOST: smtp.example.org
  EMAIL_HOST_USER: user_changeme
  EMAIL_HOST_PASSWORD: password_changeme
  EMAIL_PORT: "465"
  EMAIL_USE_SSL: "True"
  EMAIL_USE_TLS: ""
  DEFAULT_FROM_EMAIL: Bugsink <bugsink@example.org>
