apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-izboljsajmo-maribor
spec:
  schedule: 56 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-izboljsajmo-maribor
            image: backup
            args:
            - /bin/bash
            - /do_backup.sh
            envFrom:
              - secretRef:
                  name: secrets-izboljsajmo-maribor-backup
            env:
              - name: DATABASE_NAME
                value: mb-initiative
              - name: S3_BACKUP_PATH
                value: s3://djnd-backups
          restartPolicy: OnFailure
