apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-parladata-bosna
spec:
  schedule: 40 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-parladata-bosna
            image: backup
            args:
            - /bin/bash
            - /do_backup.sh
            envFrom:
              - secretRef:
                  name: secrets-backup
            env:
              - name: DATABASE_NAME
                value: parladata_bih
              - name: S3_BACKUP_PATH
                value: s3://djnd-backups
          restartPolicy: OnFailure
