apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-plausible-clickhouse
spec:
  schedule: 20 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-plausible-clickhouse
            image: clickhouse-backup
            command:
            - bash
            - -c
            - ./do_clickhouse_backup.sh
            envFrom:
              - secretRef:
                  name: secrets-backup
              - secretRef:
                  name: secrets-clickhouse-backup
            env:
              - name: CLICKHOUSE_HOST
                value: chi-clickhouse-simple-0-0.shared
              - name: DATABASE_NAME
                value: plausible
              - name: S3_BACKUP_PATH
                value: s3://djnd-backups
          restartPolicy: OnFailure
