apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:

  # postgis
  # - backups/db/backup-izboljsajmo-maribor.yaml # NO LONGER DEPLOYED

  # mariadb
  - backups/db/backup-brezkvasa.yaml
  - backups/db/backup-mautic.yaml
  - backups/db/backup-zvizgac.yaml

  # clickhouse
  - backups/db/backup-plausible-clickhouse.yaml

  # postgres 16
  - backups/db/backup-bojkot.yaml
  - backups/db/backup-cnvos-acf.yaml
  - backups/db/backup-cnvos.yaml
  - backups/db/backup-consul-ankaran.yaml
  - backups/db/backup-consul-celje.yaml
  - backups/db/backup-consul-koper.yaml
  # - backups/db/backup-consul-maribor.yaml # NO LONGER DEPLOYED
  - backups/db/backup-consul-medvode.yaml
  - backups/db/backup-consul-nova-gorica.yaml
  - backups/db/backup-consul-novo-mesto.yaml
  - backups/db/backup-consul-rog.yaml
  - backups/db/backup-consul-staging.yaml
  - backups/db/backup-consul-trebnje.yaml
  - backups/db/backup-consul-trzic.yaml
  - backups/db/backup-danesjenovdan-si.yaml
  - backups/db/backup-disco.yaml
  - backups/db/backup-dobrodelen.yaml
  - backups/db/backup-glasljudstva.yaml
  - backups/db/backup-hudapobuda.yaml
  - backups/db/backup-izvoli-eu.yaml
  - backups/db/backup-krtk.yaml
  - backups/db/backup-kvak.yaml
  - backups/db/backup-lesson-plans.yaml
  - backups/db/backup-melita.yaml
  - backups/db/backup-mirovniki.yaml
  - backups/db/backup-najemniski-sos.yaml
  # - backup-newsgradient.yaml archived
  - backups/db/backup-novdan.yaml
  - backups/db/backup-obljubadeladolg.yaml
  - backups/db/backup-odprti-racuni-obcine.yaml
  - backups/db/backup-odprti-racuni.yaml
  - backups/db/backup-parladata-ajdovscina.yaml
  - backups/db/backup-parladata-bosna.yaml
  - backups/db/backup-parladata-hrastnik.yaml
  - backups/db/backup-parladata-hrvaska.yaml
  - backups/db/backup-parladata-lendava.yaml
  - backups/db/backup-parladata-ljubljana.yaml
  - backups/db/backup-parladata-medvode.yaml
  - backups/db/backup-parladata-slovenija.yaml
  - backups/db/backup-parladata-ua.yaml
  - backups/db/backup-parlameter-trbovlje.yaml
  - backups/db/backup-parlameter-zagreb.yaml
  - backups/db/backup-penpot.yaml
  - backups/db/backup-plausible.yaml
  - backups/db/backup-podpri-pic.yaml
  - backups/db/backup-podpri.yaml
  - backups/db/backup-ppp-hr.yaml
  - backups/db/backup-ppp.yaml
  - backups/db/backup-pravnamreza.yaml
  - backups/db/backup-rog-stage.yaml
  - backups/db/backup-rog.yaml
  - backups/db/backup-stanovanjske-zadruge-zemljevid.yaml
  - backups/db/backup-stanovanjskiblok.yaml
  - backups/db/backup-twito.yaml
  - backups/db/backup-vinopolis.yaml
  - backups/db/backup-weblate.yaml
  - backups/db/backup-wiki-outline.yaml
  - backups/db/backup-zip.yaml
  - backups/db/backups-cleaner.yaml

  #TODO
  # consul_hrpelje_kozina

images:
  - name: backup-mariadb
    newName: rg.fr-par.scw.cloud/djnd/backup-mariadb
    newTag: '6af374eb92b2cbba7fb1f68a875631bb93c5cbb8'
  - name: clickhouse-backup
    newName: rg.fr-par.scw.cloud/djnd/clickhouse-backup
    newTag: '6af374eb92b2cbba7fb1f68a875631bb93c5cbb8'
  - name: backup-pg-16
    newName: rg.fr-par.scw.cloud/djnd/backup-pg-16
    newTag: '6af374eb92b2cbba7fb1f68a875631bb93c5cbb8'
  - name: backups-cleaner
    newName: rg.fr-par.scw.cloud/djnd/backups-cleaner
    newTag: '6af374eb92b2cbba7fb1f68a875631bb93c5cbb8'
  - name: backup-static-files
    newName: rg.fr-par.scw.cloud/djnd/backup-static-files
    newTag: '6af374eb92b2cbba7fb1f68a875631bb93c5cbb8'
