apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - backup-hudapobuda.yaml
  - backup-izboljsajmo-maribor.yaml
  - backup-mautic.yaml
  - backup-najemniski-sos.yaml
  - backup-newsgradient.yaml
  - backup-novdan.yaml
  - backup-obljubadeladolg.yaml
  - backup-parladata-ajdovscina.yaml
  - backup-parladata-bosna.yaml
  - backup-parladata-hrastnik.yaml
  - backup-parladata-lendava.yaml
  - backup-parladata-slovenija.yaml
  - backup-parladata-hrvaska.yaml
  - backup-parladata-ua.yaml
  - backup-parladata-medvode.yaml
  - backup-plausible-clickhouse.yaml
  - backup-plausible.yaml
  - backup-pravnamreza.yaml
  - backup-wiki.yaml
  - backup-odprti-racuni.yaml
  - backup-ppp.yaml
  - backup-ppp-hr.yaml
  - backup-rog.yaml
  # postgres 15
  - backup-danesjenovdan-si.yaml
  - backup-consul-rog.yaml
  - backup-consul-trzic.yaml
  - backup-consul-nova-gorica.yaml
  - backup-consul-novo-mesto.yaml
  - backup-parlameter-trbovlje.yaml
  - backup-izvoli-eu.yaml
  - backup-weblate.yaml
images:
  - name: backup
    newName: rg.fr-par.scw.cloud/djnd/backup
    newTag: 'e30ae6ee87e284695cdf86e650e07fbcfb59044c'
  - name: backup-mb
    newName: rg.fr-par.scw.cloud/djnd/backup-postgis-13
    newTag: 'e30ae6ee87e284695cdf86e650e07fbcfb59044c'
  - name: backup-mariadb
    newName: rg.fr-par.scw.cloud/djnd/backup-mariadb
    newTag: 'e30ae6ee87e284695cdf86e650e07fbcfb59044c'
  - name: clickhouse-backup
    newName: rg.fr-par.scw.cloud/djnd/clickhouse-backup
    newTag: 'e30ae6ee87e284695cdf86e650e07fbcfb59044c'
  - name: backup-pg-15
    newName: rg.fr-par.scw.cloud/djnd/backup-pg-15
    newTag: 'e30ae6ee87e284695cdf86e650e07fbcfb59044c'
  - name: backup-pg-15
    newName: rg.fr-par.scw.cloud/djnd/backup-pg-15
    newTag: 'e30ae6ee87e284695cdf86e650e07fbcfb59044c'
