apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - backup-hudapobuda.yaml
  - backup-najemniski-sos.yaml
  - backup-newsgradient.yaml
  - backup-novdan.yaml
  - backup-obljubadeladolg.yaml
  - backup-parladata-ajdovscina.yaml
  - backup-parladata-hrastnik.yaml
  - backup-parladata-lendava.yaml
  - backup-parladata-ua.yaml
  - backup-parladata-slovenija.yaml
  - backup-parladata-bosna.yaml
  - backup-plausible.yaml
  - backup-pravnamreza.yaml
  - backup-wiki.yaml
  - backup-izboljsajmo-maribor.yaml
images:
- name: backup
  newName: rg.fr-par.scw.cloud/djnd/backup
  newTag: 'latest'
- name: backup-mb
  newName: rg.fr-par.scw.cloud/djnd/backup-postgis-13
  newTag: 'latest'
