apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - backup-newsgradient.yaml
  - backup-plausible.yaml
  - backup-obljubadeladolg.yaml
  - backup-hudapobuda.yaml
  - backup-wiki.yaml
  - backup-pravnamreza.yaml
  - backup-parladata-ua.yaml
  - backup-parladata-ajdovscina.yaml
  - backup-parladata-hrastnik.yaml
images:
- name: backup
  newName: rg.fr-par.scw.cloud/djnd/backup
  newTag: 'latest'
