apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - backup-hudapobuda.yaml
  - backup-izboljsajmo-maribor.yaml
  - backup-mautic.yaml
  - backup-najemniski-sos.yaml
  - backup-newsgradient.yaml
  - backup-novdan.yaml
  - backup-obljubadeladolg.yaml
  - backup-parladata-ajdovscina.yaml
  - backup-parladata-bosna.yaml
  - backup-parladata-hrastnik.yaml
  - backup-parladata-lendava.yaml
  - backup-parladata-slovenija.yaml
  - backup-parladata-ua.yaml
  - backup-plausible-clickhouse.yaml
  - backup-plausible.yaml
  - backup-pravnamreza.yaml
  - backup-wiki.yaml
images:
  - name: backup
    newName: rg.fr-par.scw.cloud/djnd/backup
    newTag: 'ddeaffff1abd494ce2b7af1800881119bf3c0a3b'
  - name: backup-mb
    newName: rg.fr-par.scw.cloud/djnd/backup-postgis-13
    newTag: 'ddeaffff1abd494ce2b7af1800881119bf3c0a3b'
  - name: backup-mariadb
    newName: rg.fr-par.scw.cloud/djnd/backup-mariadb
    newTag: 'ddeaffff1abd494ce2b7af1800881119bf3c0a3b'
  - name: clickhouse-backup
    newName: rg.fr-par.scw.cloud/djnd/clickhouse-backup
    newTag: 'ddeaffff1abd494ce2b7af1800881119bf3c0a3b'
