apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - backup-pravnamreza.yaml
  - backup-wiki.yaml
images:
- name: backup
  newName: rg.fr-par.scw.cloud/djnd/backup
  newTag: '87215625e8604def60f99a80819f5442f1adb05c'
