apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  
  # postgis
  - backup-izboljsajmo-maribor.yaml

  # mariadb
  - backup-mautic.yaml

  # clickhouse
  - backup-plausible-clickhouse.yaml

  # postgres 11 wating to be "upgraded"
  - backup-plausible.yaml

  # postgres 15

  - backup-cnvos-acf.yaml
  - backup-cnvos.yaml
  - backup-consul-koper.yaml
  - backup-consul-maribor.yaml
  - backup-consul-medvode.yaml
  - backup-consul-nova-gorica.yaml
  - backup-consul-novo-mesto.yaml
  - backup-consul-rog.yaml
  - backup-consul-staging.yaml
  - backup-consul-trebnje.yaml
  - backup-consul-trzic.yaml
  - backup-danesjenovdan-si.yaml
  - backup-disco.yaml
  - backup-dobrodelen.yaml
  - backup-glasljudstva.yaml
  - backup-hudapobuda.yaml
  - backup-izvoli-eu.yaml
  - backup-lesson-plans.yaml
  - backup-melita.yaml
  - backup-najemniski-sos.yaml
  # - backup-newsgradient.yaml archived
  - backup-novdan.yaml
  - backup-obljubadeladolg.yaml
  - backup-odprti-racuni-obcine.yaml
  - backup-odprti-racuni.yaml
  - backup-parladata-ajdovscina.yaml
  - backup-parladata-bosna.yaml
  - backup-parladata-hrastnik.yaml
  - backup-parladata-hrvaska.yaml
  - backup-parladata-lendava.yaml
  - backup-parladata-ljubljana.yaml
  - backup-parladata-medvode.yaml
  - backup-parladata-slovenija.yaml
  - backup-parladata-ua.yaml
  - backup-parlameter-trbovlje.yaml
  - backup-penpot.yaml
  - backup-podpri.yaml
  - backup-ppp-hr.yaml
  - backup-ppp.yaml
  - backup-pravnamreza.yaml
  - backup-rog-stage.yaml
  - backup-rog.yaml
  - backup-stanovanjske-zadruge-zemljevid.yaml
  - backup-twito.yaml
  - backup-vinopolis.yaml
  - backup-weblate.yaml
  - backup-wiki-outline.yaml
  

  #TODO
  # consul_hrpelje_kozina

images:
  - name: backup
    newName: rg.fr-par.scw.cloud/djnd/backup
    newTag: '067734b778e63b86933580c59c49d301ed2dee4a'
  - name: backup-mb
    newName: rg.fr-par.scw.cloud/djnd/backup-postgis-13
    newTag: '067734b778e63b86933580c59c49d301ed2dee4a'
  - name: backup-mariadb
    newName: rg.fr-par.scw.cloud/djnd/backup-mariadb
    newTag: '067734b778e63b86933580c59c49d301ed2dee4a'
  - name: clickhouse-backup
    newName: rg.fr-par.scw.cloud/djnd/clickhouse-backup
    newTag: '067734b778e63b86933580c59c49d301ed2dee4a'
  - name: backup-pg-15
    newName: rg.fr-par.scw.cloud/djnd/backup-pg-15
    newTag: '067734b778e63b86933580c59c49d301ed2dee4a'
