apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: google-workspace-redirects
    newName: rg.fr-par.scw.cloud/djnd/google-workspace-redirects
    newTag: "latest"
