apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore-mirovniki-pvc
  labels:
    app: odoo-mirovniki
spec:
  storageClassName: "scw-bssd-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
