apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-rog-stage
spec:
  schedule: 1 10 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rog-stage
            image: backup-pg-16
            args:
            - /bin/bash
            - /do_backup.sh
            envFrom:
              - secretRef:
                  name: secrets-backup-common
              - secretRef:
                  name: secrets-backup-postgres
            env:
              - name: DATABASE_NAME
                value: rog_stage
              - name: S3_BACKUP_PATH
                value: s3://djnd-backups
          restartPolicy: OnFailure
