apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-najemniski-sos
spec:
  schedule: 30 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-najemniski-sos
            image: backup-pg-16
            args:
            - /bin/bash
            - /do_backup.sh
            envFrom:
              - secretRef:
                  name: secrets-backup-common
              - secretRef:
                  name: secrets-backup-postgres
            env:
              - name: DATABASE_NAME
                value: najemniski-sos
              - name: S3_BACKUP_PATH
                value: s3://djnd-backups
          restartPolicy: OnFailure
