apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-danesjenovdan-si
spec:
  schedule: 21 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: danesjenovdan-si
            image: backup-pg-15
            args:
            - /bin/bash
            - /do_backup.sh
            envFrom:
              - secretRef:
                  name: secrets-backup-pg-15
            env:
              - name: DATABASE_NAME
                value: danesjenovdan_si
              - name: S3_BACKUP_PATH
                value: s3://djnd-backups
          restartPolicy: OnFailure
