apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kimai-data-pvc
  labels:
    app: kimai
spec:
  storageClassName: "scw-bssd-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
