apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblate-pvc
  labels:
    app: weblate
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: "scw-bssd-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
