apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != "wiki.danesjenovdan.si") {
        rewrite ^/(.*) $scheme://wiki.danesjenovdan.si/$1 permanent;
      }
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - wiki.danesjenovdan.si
    secretName: wiki-tls
  rules:
  - host: wiki.danesjenovdan.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: outline
            port:
              number: 80
