apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
- name: outline
  newName: outlinewiki/outline
  newTag: 'latest'