apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-outline
spec:
  template:
    spec:
      containers:
      - name: migrate-outline
        image: outlinewiki/outline:latest
        command: ['yarn', 'sequelize:migrate', '--env=production-ssl-disabled']
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: secretKey
          - name: UTILS_SECRET
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: utilsSecret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: databaseUrl
          - name: DATABASE_URL_TEST
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: databaseUrlTest
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: redisUrl
          - name: URL
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: url
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: port
          - name: SLACK_KEY
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: slackKey
          - name: SLACK_SECRET
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: slackSecret
          - name: SLACK_VERIFICATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: slackVerificationToken
          - name: SLACK_APP_ID
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: slackAppId
          - name: SLACK_MESSAGE_ACTIONS
            value: "true"
          - name: FORCE_HTTPS
            value: "false"
          - name: ENABLE_UPDATES
            value: "true"
          - name: DEBUG
            value: "cache,presenters,events,emails,mailer,utils,multiplayer,server,services"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: awsAccessKeyId
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: awsSecretAccessKey
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: awsRegion
          - name: AWS_S3_UPLOAD_BUCKET_URL
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: awsS3UploadBucketUrl
          - name: AWS_S3_UPLOAD_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: awsS3UploadBucketName
          - name: AWS_S3_UPLOAD_MAX_SIZE
            value: "26214400"
          - name: AWS_S3_FORCE_PATH_STYLE
            value: "false"
          - name: AWS_S3_ACL
            value: private
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: smtpHost
          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: smtpPort
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: smtpUsername
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: smtpPassword
          - name: SMTP_FROM_EMAIL
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: smtpFromEmail
          - name: SMTP_REPLY_EMAIL
            valueFrom:
              secretKeyRef:
                name: outline-env
                key: smtpReplyEmail
          - name: DEFAULT_LANGUAGE
            value: en_US
          - name: PGSSLMODE
            value: disable
      restartPolicy: Never
  backoffLimit: 4
