apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: uptime-kuma
    newName: louislam/uptime-kuma
    newTag: "1.23.16-alpine"
