apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  labels:
    app: uptime-kuma
  # annotations:
  #   pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: "scw-bssd-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
