apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: valkey
    newName: valkey/valkey
    newTag: "7.2.10-alpine"
