apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - backup-mautic.yaml

images:
  - name: backup-static-files
    newName: rg.fr-par.scw.cloud/djnd/backup-static-files
    newTag: 'latest'
