name: Build and publish Docker image
on:
  push:
    branches:
      - 'k8s'
jobs:
  push_to_registry:
    name: Build and push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Scaleway
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/djnd
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Build and push postgis backup
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/backup-postgis-13.Dockerfile
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/backup-postgis-13:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/backup-postgis-13:latest

      - name: Build and push mariadb backup
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/backup-mariadb.Dockerfile
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/backup-mariadb:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/backup-mariadb:latest

      - name: Build and push clickhouse backup
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/clickhouse-backup.Dockerfile
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/clickhouse-backup:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/clickhouse-backup:latest

      - name: Update image versions in kustomize/kustomization.yaml
        run: |
          sed -i "s/newTag: .*\+/newTag\: '${{ github.sha }}'/" kustomize/kustomization.yaml

      - name: Commit and push new image versions
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Update image versions in kustomize/kustomization.yaml'

      - name: Build and push backup-pg-15
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/backup-postgres-15.Dockerfile
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/backup-pg-15:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/backup-pg-15:latest

      - name: Build and push backups-cleaner
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/backups-cleaner.Dockerfile
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/backups-cleaner:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/backups-cleaner:latest

      - name: Build and push backup-static-files
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/backup-static-files.Dockerfile
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/backup-static-files:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/backup-static-files:latest
