apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-djnd
  labels:
    app: mariadb-djnd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-djnd
  template:
    metadata:
      labels:
        app: mariadb-djnd
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mariadb-djnd
                topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-djnd-pvc
      containers:
        - name: mariadb-djnd
          image: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mariadb-auth
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - mariadb-admin -u root -p${MARIADB_ROOT_PASSWORD} ping
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - mariadb -u root -p${MARIADB_ROOT_PASSWORD} -e "SELECT 1"
            periodSeconds: 10
            failureThreshold: 60 # 60x10 = 600s = 10min to startup
