apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
images:
  - name: mariadb
    newName: library/mariadb
    newTag: "12.0.2"
