apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-djnd-pvc
  labels:
    app: mariadb-djnd
spec:
  storageClassName: "scw-bssd-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
